Changed build.xml so that the jar contains also all dependent classes. This should resolve the NoClassDefFoundError.
Inspired by: https://stackoverflow.com/questions/18451052/how-to-include-jars-in-lib-into-project-jar-file-in-netbeans/30172972